### ISSUE TITLE
More Info needed

### ISSUE THREAD

**Issue by kamoteshake** [3dymy/RampsPlus2#1]
Hi there,

I've been searching hours about the RAMPS plus2 but I only see this and a site where to buy it. Do you have some more information about this board? Like schematics and maybe specs? maybe the pins information too?

thanks.

**Comment by blairq** [comment]
we really need the schematics

**Comment by designkase** [comment]
I am trying to install a new bootloader but don't know the pin outs.  Can you PLEASE PROVIDE!!
